siteName: Higher Wage Wisconsin
primaryColor: '#71C0A7'
accentColor: '#737373'
navLinks:
  - label: Home
    href: /
    external: false
  - label: Higher Wage Wisconsin
    href: /#higher-wage
    external: false
  - label: Contact
    href: /#contact
    external: false
socialLinks: []
businessGridColumns: '2'
businessPlaceholderText: Business Logo
showGoalsSection: true
showHowItWorksSection: true
siteDescription: >-
  Highlighting Wisconsin businesses that voluntarily pay their employees above
  the minimum wage.
