siteName: Higher Wage Wisconsin
tagline: Showcasing businesses who are opting into a higher minimum wage.
siteLogo: /images/site/siteLogo.png
favicon: /images/site/favicon.png
theme: rose
navLinks:
  - label: Home
    href: /
    external: false
  - label: Higher Wage Wisconsin
    href: /#higher-wage
    external: false
  - label: Contact
    href: /#contact
    external: false
socialLinks: []
businessGridColumns: '2'
businessPlaceholderText: Business Logo
showGoalsSection: true
showHowItWorksSection: true
siteDescription: >-
  Highlighting Wisconsin businesses that voluntarily pay their employees above
  the minimum wage.
